### ISSUE TITLE
Release builds are linking with debug libraries

### ISSUE THREAD

**Issue by codecat** [godotengine/godot-cpp#917] opened 2022-11-08 22:19 UTC
Since updating for Godot 4 beta 4 support, users have been reporting an issue where my builds produced using `template_release` are linked with debug runtime libraries: https://github.com/codecat/godot-tbloader/issues/36

This might be related to #867, but I don't really know enough about SCons to properly debug this. I believe my SCons file is properly configured though, so this might be a bug in godot-cpp?

**Comment by akien-mga** [comment] 2022-11-11 12:03
Was this not a bug in your SConstruct that was fixed by https://github.com/codecat/godot-tbloader/commit/845a29a917858856142baf6f63b51716fd669cb9 ?

**Comment by codecat** [comment] 2022-11-11 12:04
That was an attempt at fixing it which sadly did not work.

**Comment by akien-mga** [comment] 2022-11-11 12:18
I'm not sure that's the source of the problem but you could try to force `debug_symbols=no` to skip this branch:
https://github.com/godotengine/godot-cpp/blob/master/tools/windows.py#L30-L31
(BTW the `target` check is wrong @Faless)

We should ensure that `debug_symbols` only affects generating and emitting debug symbols, like in upstream Godot. We currently don't have flags that make MSVC use `/MDd` in Godot (it could for `dev_build`, but `debug_symbols` should stay something "extra" that generates symbols that can be used or not - i.e. when not shipping the pdb, it should behave like a build without debug symbols).

**Comment by codecat** [comment] 2022-11-11 12:33
Using `debug_symbols=no` seems to work around this and properly links to the release dll's. 👍 This is a good workaround for me now, thank you!

**Closed** 2022-11-21 10:39 UTC
Labels: bug, platform:windows, buildsystem
