### ISSUE TITLE
4.0 RC 2: Object::cast_to<() returns nullpr

### ISSUE THREAD

**Issue by sash-rc** [godotengine/godot-cpp#1043] opened 2023-02-15 10:45 UTC
4.0 RC 2 (Linux x86_64 gcc)

    auto node1 = get_node_or_null("gui"); // valid
    auto node2 = Object::cast_to<Control>(node1); // nullpr
    auto node3 = get_node<Control>("gui"); // nullpr

**Comment by Withaust** [comment] 2023-02-15 11:17
Also broken by https://github.com/godotengine/godot-cpp/pull/1037

**Comment by sash-rc** [comment] 2023-02-15 21:11
@dsnopek 
Sorry, I don't use SCons for my projects. But to reproduce a case, in a stock demo project, in `test/src/example.cpp`
append this code to `void Example::_notification(int p_what)` (line 52)

```cpp
if  (p_what == NOTIFICATION_READY) {
  auto just_node = get_node_or_null("Label");
  auto label_node = get_node<Label>("Label");
  auto cast_node = cast_to<Label>(just_node);
  UtilityFunctions::print("NOTIFICATION_READY, just_node: ", just_node, " label_node: ", label_node, " cast_node: ", cast_node);
}
```
It prints
> NOTIFICATION_READY, just_node: Label:<Label#26608664999> label_node: <Object#null> cast_node: <Object#null>

Built with "editor" target, if this matters.

**Comment by dsnopek** [comment] 2023-02-16 00:40
@sash-rc In your example, how is the "Label" node created?

**Comment by sash-rc** [comment] 2023-02-16 08:59
@dsnopek 
> how is the "Label" node created?

It's a part of demo scene, a child of Example node. Stored in `test/demo/main.tscn`

**Comment by dsnopek** [comment] 2023-02-16 13:06
> It's a part of demo scene, a child of Example node. Stored in `test/demo/main.tscn`

Oh, ok, you're using the demo project in this repo! Sorry, I didn't pick up on that from your original comment. Thanks!

**Comment by codecat** [comment] 2023-02-17 00:11
This caused some issues in TBLoader as well: https://github.com/codecat/godot-tbloader/issues/68 and https://github.com/codecat/godot-tbloader/issues/69

**Comment by zhehangd** [comment] 2023-02-17 05:19
This happened to me when I tried to cast a loaded .tscn from Ref<Resource> to Ref<PackedScene> in cpp.

**Comment by RonYanDaik** [comment] 2023-02-19 13:15
on windows
```
Object* oub = Object::cast_to<Object>((Object*)selected_array[x]); //success
Node* noub = Node::cast_to<Node>((Object*)selected_array[x]);	  //failure
Node* noub2 = Node::cast_to<Node>(selected_array[x]);			  //failure

//- then ---------------------------------------------------------------------------------
Node3D* nub = (Node3D*)(oub);											//success
Node3D* nub2 = Node3D::cast_to<Node3D>(oub);						//failure

//-- and to test if cast_to is working at all --------------------------------------------
Node* tub = nub->find_child("UnitBase");							//success
Node3D* ub = Object::cast_to<Node3D>(tub);						//success

```

**Comment by dsnopek** [comment] 2023-02-19 15:30
FYI, the change that is causing these issues is going to be reverted (Remi approved it but hasn't gotten around to merging it yet):

https://github.com/godotengine/godot-cpp/pull/1046

I do have a set of PR's that fix these regressions without reverting (since reverting will add some other bugs back :-)), but the changes are too big with 4.0's imminent release.

In any case, thanks for the extra info on how to reproduce, but this issue should be fixed very soon once the revert PR is merged. :-)

**Closed** 2023-02-20 09:09 UTC
Labels: bug, regression
