### ISSUE TITLE
Crash when calling play() method from C++, AnimationPlayer, AudioStreamPlayer

### ISSUE THREAD

**Issue by RhapsodyInGeek** [godotengine/godot-cpp#1107] opened 2023-05-03 08:52 UTC
Game crashes when calling `play()` from an AnimationPlayer, AudioStreamPlayer3D, AudioStreamPlayer2D, or AudioStreamPlayer via a GDExtension Class. Log provides the following error:
```
USER ERROR: Hash mismatch for method 'AnimationPlayer.play'.
   at: gdextension_classdb_get_method_bind (core/extension/gdextension_interface.cpp:990)
```
This occurs in both mono and standard Godot 4.0.2 versions. It seems to have been introduced in 4.0.2, as the `play()` method functions properly in 4.0.1 and 4.0. The crash only happens when the method is called from C++; GDScript calls function normally with no apparent issues. I have not tested calling from C#.

Strangely enough, no other methods seemed to cause any issues with those nodes: only `play()`. Have not tested any other nodes that have a `play()` method.

**Comment by dsnopek** [comment] 2023-05-03 14:58
This is related to issue https://github.com/godotengine/godot/issues/75779

Until this is resolved (if it's resolved - there is some discussion about that on the issue), you'll need to recompile your GDExtension using the latest godot-cpp on the 4.0 branch in order for it to work with Godot 4.0.2

**Comment by Calinou** [comment] 2023-05-03 17:39
- Duplicate of https://github.com/godotengine/godot/issues/75779.

**Closed by Calinou** 2023-05-03 17:39 UTC
