### ISSUE TITLE
Godot editor crash caused by custom `AudioStream` in GDExtension

### ISSUE THREAD

**Issue by oparisy** [godotengine/godot-cpp#1207] opened 2023-08-12 15:49 UTC
### Godot version

v4.1.1.stable.official [bd6af8e0e]

### godot-cpp version

4.1

### System information

Windows 11, Intel Core i7-8665U. Visual Studio 2022 C++ toolchain (through `scons`).

### Issue description

While writing a GDExtension providing a custom `AudioStream` (essentially a port of [this tutorial](https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/custom_audiostreams.html)), I faced Godot editor crashes when testing it.

After noticing that adding code from [DeleteSystem32/godot-flac-extension](https://github.com/DeleteSystem32/godot-flac-extension) "fixed" the crash, I bissected until I could conclude that including `audio_frame.hpp` in the `register_types.cpp` of my GDExtension was required.

So I have a workaround, but it does not make much sense: including this header is not required for the code to compile, and this header is added last so it cannot influence any of the other `.hpp` included in `register_types.cpp`. Finally `audio_stream.hpp` is already included in all the `.cpp` files of my GDExtension that need it to compile properly, so it seems superfluous.

Ultimately I think there is something fishy here, and it will be a hindrance to people developping custom `AudioStream` subclasses since I only discovered this workaround by accident. 

### Steps to reproduce

How to reproduce:
1. Compile the provided project by typing `scons`.
2. Open `game/project.godot` in Godot v4.1.1.stable.
3. Click the "Playing" property in the Inspector (for node `AudioStreamPlayerSimple`).
4. Notice that no sound is emitted.
5. The Godot editor crashes after a moment.

Workaround:
1. Uncomment `#include <godot_cpp/classes/audio_frame.hpp>` in `register_types.cpp` (there's a TODO just before).
2. Compile using `scons`.
3. Open the project in Godot.
4. Click the "Playing" property: some sound is emitted. The editor does not crash.
5. You can also run the project (F5): the sound is generated, and nothing crashes either.

### Minimal reproduction project

[GDExtensionMyToneMRE.zip](https://github.com/godotengine/godot-cpp/files/12327718/GDExtensionMyToneMRE.zip)

Here is a minimum reproduction project. I took the liberty to leave the `.godot` folder as it makes reproduction steps simpler (the proper node is selected, etc.), while striving to keep the archive as small as possible.

**Comment by vorlac** [comment] 2023-08-13 07:50
I ended up looking into this crash a bit today after it came up in discord. Here's a repo set up to run the sample project but will set everything up automatically to run it with a debug build of the engine (using cmake & vs2022, windows only):
https://github.com/vorlac/godot-audio-stream

The crash happens when [this](https://github.com/vorlac/godot-audio-stream/blob/35311c1b8b27fe1238dc4c63931087192a22da97/src/audiostream_simple.h#L69) virtual override of `_mix` is called from `void AudioServer::_mix_step()`.

The issue that leads to the crash seems to be caused by the compiler choosing the wrong specialization for `PtrToArg<>` when evaluating the `AudioFrame*` in the parameter list of `_mix` in this extension. If `#include <godot_cpp/classes/audio_frame.hpp>` isn't included early enough, the correct specialization won't be defined by `GDVIRTUAL_NATIVE_PTR(AudioFrame)` before the build of godot-cpp needs it. The issue then becomes that it ends up choosing the pretty generic specialization of `template <class T> PtrToArg<T*>` defined for `godot::Object` derived classes (`AudioFrame` is just a simple struct that doesn't inherit from anything). The compiler choosing the wrong specialization leads to it `reinterpret_cast`'ing the `AudioFrame*` into a `godot::Object*`, which just leads to a corrupt `godot::Object`. I'm guessing it only gets away with that because `GDExtensionObjectPtr` is defined as `void*` so the compiler doesn't complain about the casts, or there are c-style casts hiding somewhere that lets it convert `AudioFrame*` to `void*` through something like `void* p = *((void**)(&audio_frame_ptr));`. 

I tested this with clang++ and msvc, both led to the same result. Here's the stack trace of the crash, and the highlighted line is the call that leads to the crash from the `ArgToPtr<>` specialization intended for `godot::Object*`...
![image](https://github.com/godotengine/godot-cpp/assets/92295044/89f2e8b7-da52-4783-a425-ee2bb135d695)

I'm still very new to the engine/bindings so I'm not really sure how to approach making this type of thing easier to catch at compile time. I'm assuming the specialization it's falling into is pretty generic for a reason, but something like `std::enable_if<>` (or concepts if the bindings code is moving to C++20 anytime soon) might be worth using to tighten up which types fall into this specialization. Or if it needs to stay as-is, there might be a way to work in a `static_assert` at the very least?

Hopefully someone with a bit more knowledge of the overall implementation of the bindings could chime in to see if/how something like this might be possible to catch at compile time.

**Comment by dsnopek** [comment] 2023-08-15 22:57
Thanks! Great catch, @oparisy & @vorlac :-)

I made a PR which fixes the MRP in my testing:

https://github.com/godotengine/godot-cpp/pull/1214

**Comment by oparisy** [comment] 2023-08-27 09:53
For reference, I've just published a GDExtension providing a minimal, custom `AudioStream`: [gdextension-custom-audiostream](https://github.com/oparisy/gdextension-custom-audiostream).

It's a cleaned up, documented version of the MRE I attached to this issue, and it integrates the workaround described here.

**Closed** 2023-09-08 15:12 UTC
Labels: bug, confirmed
