### ISSUE TITLE
Compiling for android Linker error

### ISSUE THREAD

**Issue by nonunknown** [godotengine/godot-cpp#474] opened 2020-11-24 14:38 UTC
I'm using the compile example in the README for android

just in the link part, the cl one works fine
```
link -o custom/libtest.so -shared custom/src/SimpleClass.o -L=bin -l=libgodot-cpp.android.release.arm64v8.a
 cannot find -l/usr/local/google/buildbot/src/android/binutils/prebuilts/ndk/current/platforms/android-21/arch-arm64libgodot-cpp.android.release.arm64v8.a
```

```
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
seems the error is on -L or -l

**Comment by Calinou** [comment] 2020-11-24 14:42
Duplicate of https://github.com/godotengine/godot-cpp/issues/364 ?

**Comment by nonunknown** [comment] 2020-11-24 23:14
yes!

**Closed** 2020-11-25 00:03 UTC
