### ISSUE TITLE
Test project builds fine but crashes when ran with official 4.0.alpha10 (both Windows and Linux)

### ISSUE THREAD

**Issue by rendawudi** [godotengine/godot-cpp#768] opened 2022-06-16 15:31 UTC
env:
vs2019 
godot-alpha10-win64
win10-sdk (10.0.19041.0)
MSVC v142
Cmake 3.23.2
Python 3.9.6

try to clone the newest code as commonds:
git clone --recursive -b master https://github.com/godotengine/godot-cpp
cd .\godot-cpp\
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_SYSTEM_NAME=Windows .
cmake --build .

then build test demo with commonds:
cd .\test
 cmake -DCMAKE_BUILD_TYPE=Release .
cmake --build .

then move and rename the .dll .exp .lib .pdb from bin to demo/bin
 libgdexample.windows.debug.x86_64.dll  
libgdexample.windows.debug.x86_64.exp
libgdexample.windows.debug.x86_64.lib
libgdexample.windows.debug.x86_64.pdb

then open godot :

Godot Engine v4.0.alpha10.official.4bbe7f0b9 - https://godotengine.org
Vulkan API 1.2.198 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2080

Editing project: C:/Users/Administrator/Downloads/gdnative_cpp_example-master/godot-cpp/test/demo (C:::Users::Administrator::Downloads::gdnative_cpp_example-master::godot-cpp::test::demo)

Godot Engine v4.0.alpha10.official.4bbe7f0b9 - https://godotengine.org
ERROR: Condition "!windows.has(p_window)" is true.
   at: window_resize (drivers/vulkan/vulkan_context.cpp:1404)
Vulkan API 1.2.198 - Using Vulkan Device #0: NVIDIA - NVIDIA GeForce RTX 2080

Constructor.
Destructor.

(crash)

**Comment by Calinou** [comment] 2022-06-16 15:49
Official Godot builds use MinGW, but you used MSVC to compile your extension. This may be the cause of the issue.

**Comment by akien-mga** [comment] 2022-06-16 16:31
I have the same problem on Linux with the official 4.0-alpha10 binaries, while a custom build from the same commit works fine. I've checked and even a custom build with `target=release_debug production=yes` (i.e. similar to official builds) works, while 4.0.alpha10.official crashes.

I'll keep investigating, maybe it's related to the GCC version used.

**Comment by akien-mga** [comment] 2022-06-16 17:26
Likely related to https://github.com/godotengine/godot/issues/61963

**Comment by oparisy** [comment] 2022-06-26 13:07
I reproduced this with Visual Studio 2022 and 4.0.alpha10.official.

The issue disappeared when compiling Godot myself with VS2022 (from the alpha10 commitId), so @Calinou analysis is certainly proper in this case.

I guess the official GDExtension documentation will need to touch on this: something along the line of "use MinGW if you did not compile Godot yourself" I guess?

**Comment by dsge** [comment] 2022-06-26 13:35
> I guess the official GDExtension documentation will need to touch on this: something along the line of "use MinGW if you did not compile Godot yourself" I guess?

That's not good enough as this also affects Linux.

**Comment by oparisy** [comment] 2022-06-26 13:39
Indeed, I was refering to my test case. It should have been "Draw attention
to a list of the compilers used for each platform official build".

Le dim. 26 juin 2022, 15:36, Gergely Sárosi ***@***.***> a
écrit :

**Comment by oparisy** [comment] 2022-06-26 14:43
@Calinou Isn't this issue contradicting with [this tweet](https://twitter.com/reduzio/status/1508036064363036674?s=20&t=b0e73JCo_JPa8oO51s1TFQ) for example? Doesn't this mean that a unique compiler per platform (the one used to build the official releases) will be usable when willing to distribute compiled extensions?

**Comment by oparisy** [comment] 2022-06-27 12:59
Maybe the statics methods issue is not present on Windows then.

Le lun. 27 juin 2022, 14:21, Teodor Potancok ***@***.***> a
écrit :

**Comment by Faless** [comment] 2022-06-27 13:43
> Doesn't this mean that a unique compiler per platform (the one used to build the official releases) will be usable when willing to distribute compiled extensions?

I don't think that's the case, the old WebRTC GDNative plugin was built with MSVC and was working with the official Godot version compiled with gcc/mingw

**Comment by alessandrofama** [comment] 2022-06-28 20:08
If this is related to https://github.com/godotengine/godot/issues/61963 then I think it could be about the ``GDNativePropertyInfo`` struct variable ``pinfo`` having garbage values for static methods without return after ``get_argument_info_func`` is called:
https://github.com/godotengine/godot/blob/f41cb30f9b7fe46a014162aba9c0e9a9697343d2/core/extension/native_extension.cpp#L55-L66

What fixes the crash for me on Windows (MSVC) and macOS (Clang) is making sure the ``GDNativePropertyInfo`` struct variable ``pi`` is initialized with some default values in [gen_argument_type_info](https://github.com/alessandrofama/godot-cpp/commit/bbced914707950823150b6cba68ec03e4aacdd6d#diff-173e5b20d5756a782208c74505c0d8c328a2ce19bc2aa4822edfdad19efb51c9) if ``p_arg`` is ``-1``, otherwise ``pi`` will stay uninitialized in the consequent call to ``call_get_argument_type_info``.

This is what I noticed by stepping in the debugger, not 100% sure as I don't fully understand GDExtension, but it's still fun trying to track down the issue. I've pushed the small change in my [branch](https://github.com/alessandrofama/godot-cpp/tree/4.x_fix_static_no_return) if anyone wants to check if it fixes the issue.

**Comment by pooroligarch** [comment] 2022-07-03 10:44
> This is what I noticed by stepping in the debugger, not 100% sure as I don't fully understand GDExtensions, but it's still fun trying to track down the issue. I've pushed the small change in my [branch](https://github.com/alessandrofama/godot-cpp/tree/4.x_fix_static_no_return) if anyone wants to check if it fixes the issue.

Your commit fixes it on Linux/GCC. You should make a PR and get it merged.

**Comment by dsge** [comment] 2022-07-03 13:15
> Your commit fixes it on Linux/GCC. You should make a PR and get it merged.

I got the same result also on Linux/GCC. 

With @alessandrofama's patch I am able to Play the test project and press the "Click me!" button on the `release_debug` editor build (alpha10), whereas without the patch the editor would crash while opening the project. The `debug` editor worked with or without the the patch, which is puzzling though.

Anyway, I too agree that he should make a PR :)

**Comment by akien-mga** [comment] 2022-07-03 19:38
Fixed by #778.

**Closed by akien-mga** 2022-07-03 19:38 UTC
Labels: bug, crash, gdextension
