### ISSUE TITLE
How to compile C++ code without closing the GoDot editor如何不关闭godot编辑器来编译c++代码

### ISSUE THREAD

**Issue by dream727** [godotengine/godot-cpp#996] opened 2023-01-16 13:04 UTC
The IDE I use is VS2022,godot's version is 3.5
This is first time i use godot-cpp,when i try to compile to dll,the IDE error  unable to open dll file that i will out,i closed the godot editor,and i try to compile again,i did it.i think the reason is when i was trying to compile,the godot editor is opening this dll,so i cant recompile.how to solution this question.
(i confess my English is very bad,forgive me,because my mother tongue is't English.)
我使用的编译器是VS2022，godot版本是3.5。
这是我第一次使用godot-cpp，当我尝试编译为dll时程序报错无法打开要输出的dll，当我将godot关闭再编译便成功了，因此我猜测是因为godot打开了这个dll导致无法重新编译，请问是否有什么方法解决这个问题

**Comment by Calinou** [comment] 2023-01-17 02:03
Duplicate of https://github.com/godotengine/godot/issues/48086.

**Closed by Calinou** 2023-01-17 02:03 UTC
