### ISSUE TITLE
Using PacketScene:: instantiate in multithreading will cause the program to crash

### ISSUE THREAD

**Issue by 1419427247** [godotengine/godot-cpp#928] opened 2022-11-17 15:02 UTC
![image](https://user-images.githubusercontent.com/33598732/202479305-4e538540-5286-4e48-a52b-e8ed25643ade.png)

Using PacketScene:: instant in multithreading will cause the program to crash

I tried to optimize the loading speed of the scenario by using multiple threads. I thought PacketScene:: instant was a thread safe method. Is this a bug
![image](https://user-images.githubusercontent.com/33598732/202481510-c1bc62ee-6285-4dfc-ae35-6f1c84f3e0c5.png)

**Comment by 1419427247** [comment] 2022-11-17 15:24
It seems that this is really a bug. I try to replicate the operation in GDScript. When my PacketScene contains CSGBox, it will cause a crash
```gdscript
var threads : Array[Thread] = [
	Thread.new(),
	Thread.new(),
]

var preset : PackedScene = preload("res://packed_scene.tscn")
func _ready():
	for thread in threads:
		thread.start(func(): while(true) : preset.instantiate())
```

**Comment by Calinou** [comment] 2022-11-17 15:38
Duplicate of https://github.com/godotengine/godot/issues/68794 (this is an engine issue).

**Closed by Calinou** 2022-11-17 15:38 UTC
