### ISSUE TITLE
Variables with wrong types become 0 instead of being cast correctly

### ISSUE THREAD

**Issue by kb173** [godotengine/godot-cpp#907] opened 2022-11-02 15:45 UTC
Say I have the following function in a GDExtension project:

```cpp
void Example::print_variables(double double_val, int int_val) {
	UtilityFunctions::print(double_val, " and ", int_val);
}
```

As expected, calling `example.print_variables(123.0, 321)` from GDScript prints "123 and 321" to the console.

However, when the types do not match (e.g. mixing up float and int), they are not properly cast automatically: the debugger does print a warning like `Narrowing conversion (float is converted to int and loses precision)`, but the output is not still "123 and 321" as I would expect. Rather, the variable with the false type is simply 0.

Example: calling `example.print_variables(123, 321)` (first argument is now int rather than float) produces "0 and 321" in the console.

This type of bug is really hard to track down in a reasonably complex project, so I would expect either a full error if the types don't match, or a better automatic conversion.

Here's a minimal reproduction (just a quick modification of the example project from this repo): [type-cast-repro.zip](https://github.com/godotengine/godot-cpp/files/9921935/type-cast-repro.zip) running it in Godot shows that, as described above, parameters with wrong types simply become 0. This is the case even if Godot's optional static typing is not used (`=` rather than `:=`).

Tested in Godot 4.0 Beta 3

**Comment by Skwint** [comment] 2022-11-13 01:21
I just ran into the exact same thing. Passing `const radius = 10` to a C++ `set_radius(real_t p_radius);` and it gets a value of 0 with no warnings or errors. It should definitely cast it. GDscript does allow you to strongly type a variable but I don't think anyone expects to _have_ to!

**Comment by DmitriySalnikov** [comment] 2022-12-20 17:05
In fact, values are not always converted to 0.
If you convert floating point numbers that are less than 0, then you get `nan`.
But if the native function accept, for example, `Vector2i`, and `GDScript` pass `Vector2(-50, 50)` as an argument, then the native function will get `Vector2i(-1035468800, 1112014848)`.

**Comment by dsnopek** [comment] 2023-05-05 19:33
This sounds like it may be a duplicate of https://github.com/godotengine/godot/issues/75757

Can you test if PR https://github.com/godotengine/godot/pull/75758 fixes it for you?

**Closed** 2023-06-19 08:39 UTC
Labels: bug, confirmed, topic:gdextension
