### ISSUE TITLE
Segfault on Linux with GDExtension that uses std::future

### ISSUE THREAD

**Issue by arnemileswinter** [godotengine/godot-cpp#1525] opened 2024-07-17 11:36 UTC
### Tested versions

linux 4.2.2-stable

### System information

Linux 6.9.6-arch1-1, g++ (GCC) 14.1.1 20240522

### Issue description

On Linux, I get a segfault from a gdextension that uses std::future

I'm launching the future with std::async and std::launch::async flag. Setting the flag to std::launch::deferred yields the same result.

No problems running this on windows with msvc, even works in browser with wasm emscripten. I don't own a mac so i cannot test it there, but i assume the behavior to be similiar there.

### Steps to reproduce

create a gdextension that launches an std::future and retrieve its result and run it.

```
std::future<int> f = std::async(std::launch::async, []{return 1;});
f.get();
```

In the demo project attached I have already set up the steps. Running the scene will reproduce the error.

To rebuild, simply clone godot-cpp into the native directory, such that the folder is native/godot-cpp/ and then run scons from within native/demo (include target api cli parameter as required).

### Minimal reproduction project (MRP)

[future-demo.zip](https://github.com/user-attachments/files/16264795/future-demo.zip)

**Comment by arnemileswinter** [comment] 2024-07-17 11:41
> Do you have exceptions set up correctly?
> 
> This should be reported in godot-cpp however as this is unrelated to the engine, will transfer the issue there

Thanks for moving this

I encountered this when following the tutorial https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

Where do i find guidance on setting up exceptions correctly?

> Do you have exceptions set up correctly?
> 
> This should be reported in godot-cpp however as this is unrelated to the engine, will transfer the issue there

> Do you have exceptions set up correctly?
> 
> This should be reported in godot-cpp however as this is unrelated to the engine, will transfer the issue there

Thanks for moving this

I encountered this when following the tutorial https://docs.godotengine.org/en/stable/tutorials/scripting/gdextension/gdextension_cpp_example.html

Where do i find guidance on setting up exceptions correctly?

**Comment by AThousandShips** [comment] 2024-07-17 11:51
You added your own code though including the STL which isn't necessarily supported, try check if this is caused by `std::future` requiring exceptions, compile *both* the engine/templates *and* the extension with `disable_exceptions=False`

**Comment by arnemileswinter** [comment] 2024-07-17 14:22
Ok with -fno-exceptions=false in the editor i got the expected results

**Comment by AThousandShips** [comment] 2024-07-17 14:23
Did you also use the `SCons` flag I showed?

Then this is likely a duplicate of the above, closing as such and see there for more details (this is an upstream issue)

**Closed by AThousandShips** 2024-07-17 14:23 UTC
Labels: needs testing

**Comment by arnemileswinter** [comment] 2024-07-17 14:27
yep i build with the scons flag

I just confirmed that with the downloadable version of godot it also works. This seems to have been an arch btw problem...

**Comment by dsnopek** [comment] 2024-07-17 15:22
FYI, there is an issue in the Arch Linux tracker about this:

https://gitlab.archlinux.org/archlinux/packaging/packages/godot/-/issues/2
