### ISSUE TITLE
Missing Object.hpp file

### ISSUE THREAD

**Issue by cs-clarence** [godotengine/godot-cpp#496] opened 2021-01-30 09:56 UTC
Compiler error:
`
../godot-cpp/src/core/Variant.cpp:8:10: fatal error: Object.hpp: No such file or directory
`
I've used CMake to build this.

**Comment by Calinou** [comment] 2021-01-30 11:44
Duplicate of https://github.com/godotengine/godot-cpp/issues/437.

**Closed by Calinou** 2021-01-30 11:44 UTC
