### ISSUE TITLE
Registered properties derived from `Resource` generate non editable fields in the editor

### ISSUE THREAD

**Issue by Flarkk** [godotengine/godot-cpp#543] opened 2021-04-11 16:25 UTC
### Steps to reproduce :

1. Register a property of any Godot type deriving from Resource. Example :
`godot::register_property<MyClass, godot::Ref<godot::StreamTexture>>("Property", &MyClass::property, godot::Variant(), GODOT_METHOD_RPC_MODE_DISABLED, GODOT_PROPERTY_USAGE_DEFAULT, GODOT_PROPERTY_HINT_RESOURCE_TYPE, "StreamTexture");`

2. The property shows in the Editor ("Script Variables" section of the node where the NativeScript is attached) but is "[null]" and not editable

### Workaround :

This compiles and shows an editable field in the Editor, although not empty by default (it holds an instance of the Resource) :
`godot::register_property<MyClass, godot::Ref<godot::StreamTexture>>("Property", &MyClass::property, godot::Variant(godot::StreamTexture::_new()));`

**Comment by Flarkk** [comment] 2022-04-16 17:00
Just to let know I'm not affected anymore by this issue in Godot 3.4.
Maybe it can be closed if other users confirm ?

**Comment by Calinou** [comment] 2022-04-16 23:07
Closing, as this seems to be resolved. Please comment with a minimal reproduction project attached if you can still reproduce this issue.

**Closed by Calinou** 2022-04-16 23:07 UTC
Labels: bug
